# The PUBLIC url of your website.
url: http://example.com:8080/

# The secret key required to upload
secret_key: "super-secret-key"

# max size in bytes (= 8 bits)
# You can convert the size on: https://convertlive.com/u/convert/bits/to/megabytes
# -1 to disable the limit
# 0 to disable the upload
max_file_size: 8192000000

# The size of the filename (without the extension)
# The name will be generated randomly, and the extension is kept
filename_size: 32

# The directory where the files will be stored
# Can be relative and absolute paths
# If the directory doesn't exist, it will be created
upload_directory: "uploads"


# The IP to listen to.
# this does NOT affect the public URL
internal_host: 0.0.0.0

# The port to listen to.
# this does NOT affect the public URL
internal_port: 8080

# The log level
# Available levels: 'critical', 'error', 'warning', 'info', 'debug', 'trace'
log_level: "info"


# Used for big files.
chunk_size: 10485760 # = 10MB



