POST http://127.0.0.1:80/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
X-API-Key: met_ta_key_ici_bibou

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain

Hello World
------WebKitFormBoundary7MA4YWxkTrZu0gW--
